# =========================================
# Localhost API Endpoints (http://localhost:3000)
# =========================================

### Get all contacts (Localhost)
GET http://localhost:3000/contacts
Accept: application/json


### Get a contact by ID - Chinedu Okoro Updated (Localhost)
GET http://localhost:3000/contacts/68b9bd5633ab395eda5c2ef6
Accept: application/json


### Get a contact by ID - Alan Turing (Localhost)
GET http://localhost:3000/contacts/68b9bd7933ab395eda5c2ef8
Accept: application/json


### Create a new contact - Promise Ezenwoke (Localhost)
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Promise",
  "lastName": "Ezenwoke",
  "email": "ezenwokeuchechukwu@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "1992-07-21T00:00:00.000Z",
  "phone": "555-345-6789",
  "address": "789 Oak St, Abuja, Nigeria"
}


### Update a contact - Update Chinedu Okoro favoriteColor to Gold (Localhost)
PUT http://localhost:3000/contacts/68bab05fbff4f64d4a2cca68
Content-Type: application/json

{
  "firstName": "Chinedu",
  "lastName": "Okoro",
  "email": "chinedu.okoro@example.com",
  "favoriteColor": "Gold",
  "birthday": "1988-03-12T00:00:00.000Z",
  "phone": "555-234-5678",
  "address": "456 Elm St, Lagos, Nigeria"
}


### Delete a contact - Delete contact by ID (Localhost)
DELETE http://localhost:3000/contacts/68bab05fbff4f64d4a2cca68
Accept: application/json



# =========================================
# Published API Endpoints (Render deployment)
# Base URL: https://cse-341-project3-zouh.onrender.com
# =========================================

### Get all contacts (Published)
GET https://cse-341-project3-zouh.onrender.com/contacts
Accept: application/json


### Get a contact by ID - Chinedu Okoro Updated (Published)
GET https://cse-341-project3-zouh.onrender.com/contacts/68b9bd5633ab395eda5c2ef6
Accept: application/json


### Get a contact by ID - Alan Turing (Published)
GET https://cse-341-project3-zouh.onrender.com/contacts/68b9bd7933ab395eda5c2ef8
Accept: application/json


### Create a new contact - Promise Ezenwoke (Published)
POST https://cse-341-project3-zouh.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Promise",
  "lastName": "Ezenwoke",
  "email": "ezenwokeuchechukwu@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "1992-07-21T00:00:00.000Z",
  "phone": "555-345-6789",
  "address": "789 Oak St, Abuja, Nigeria"
}


### Update a contact - Update Chinedu Okoro favoriteColor to Gold (Published)
PUT https://cse-341-project3-zouh.onrender.com/contacts/68bab05fbff4f64d4a2cca68
Content-Type: application/json

{
  "firstName": "Chinedu",
  "lastName": "Okoro",
  "email": "chinedu.okoro@example.com",
  "favoriteColor": "Gold",
  "birthday": "1988-03-12T00:00:00.000Z",
  "phone": "555-234-5678",
  "address": "456 Elm St, Lagos, Nigeria"
}


### Delete a contact - Delete contact by ID (Published)
DELETE https://cse-341-project3-zouh.onrender.com/contacts/68bab2c5d87ea06beb34838d
Accept: application/json
